CREATE TRIGGER [delete_patient_cascade]
BEFORE DELETE
ON [PATIENT_DIMENSION]
FOR EACH ROW
BEGIN
DELETE FROM VISIT_DIMENSION WHERE VISIT_DIMENSION.PATIENT_NUM = old.PATIENT_NUM;
DELETE FROM USER_PATIENT_LOOKUP WHERE USER_PATIENT_LOOKUP.PATIENT_NUM = old.PATIENT_NUM;
END