CREATE VIEW patient_list
AS

SELECT
	PATIENT_DIMENSION.PATIENT_NUM as PATIENT_NUM,
	PATIENT_DIMENSION.PATIENT_CD as PATIENT_CD,
	USER_PATIENT_LOOKUP.USER_ID as USER_ID,
	PATIENT_DIMENSION.VITAL_STATUS_CD as VITAL_STATUS_CD,
	CD1.NAME_CHAR as VITAL_STATUS_RESOLVED,
	PATIENT_DIMENSION.BIRTH_DATE as BIRTH_DATE,
	PATIENT_DIMENSION.SEX_CD as SEX_CD,
	CD2.NAME_CHAR as SEX_RESOLVED,
	PATIENT_DIMENSION.AGE_IN_YEARS as AGE_IN_YEARS,
	PATIENT_DIMENSION.LANGUAGE_CD as LANGUAGE_CD,
	CD3.NAME_CHAR as LANGUAGE_RESOLVED,
	PATIENT_DIMENSION.RACE_CD as RACE_CD, 
	CD4.NAME_CHAR as RACE_RESOLVED,
	PATIENT_DIMENSION.MARITAL_STATUS_CD as MARITAL_STATUS_CD, 
	CD5.NAME_CHAR as MARITAL_STATUS_RESOLVED,
	PATIENT_DIMENSION.RELIGION_CD as RELIGION_CD,
	CD6.NAME_CHAR as RELIGION_RESOLVED,
	PATIENT_DIMENSION.STATECITYZIP_PATH as STATECITYZIP_PATH,
	PATIENT_DIMENSION.PATIENT_BLOB as PATIENT_BLOB

FROM 
	PATIENT_DIMENSION  
	
LEFT JOIN CONCEPT_DIMENSION AS CD1 ON
	CD1.CONCEPT_CD = PATIENT_DIMENSION.VITAL_STATUS_CD
LEFT JOIN CONCEPT_DIMENSION AS CD2 ON
	CD2.CONCEPT_CD = PATIENT_DIMENSION.SEX_CD
LEFT JOIN CONCEPT_DIMENSION AS CD3 ON
	CD3.CONCEPT_CD = PATIENT_DIMENSION.LANGUAGE_CD
LEFT JOIN CONCEPT_DIMENSION AS CD4 ON
	CD4.CONCEPT_CD = PATIENT_DIMENSION.RACE_CD
LEFT JOIN CONCEPT_DIMENSION AS CD5 ON
	CD5.CONCEPT_CD = PATIENT_DIMENSION.MARITAL_STATUS_CD
LEFT JOIN CONCEPT_DIMENSION AS CD6 ON
	CD6.CONCEPT_CD = PATIENT_DIMENSION.RELIGION_CD
	
LEFT JOIN USER_PATIENT_LOOKUP ON
		USER_PATIENT_LOOKUP.PATIENT_NUM = PATIENT_DIMENSION.PATIENT_NUM
	
ORDER BY	PATIENT_CD