version: '3'

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER:  user1 
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: app_db
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
     - ./data:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db: