//some constants
export const SQLite_QUERY = {
    CODE_LOOKUP: 'CREATE TABLE "CODE_LOOKUP" ( "TABLE_CD" TEXT DEFAULT NULL, "COLUMN_CD"	TEXT DEFAULT NULL, "CODE_CD" TEXT UNIQUE, "NAME_CHAR" TEXT DEFAULT NULL, "LOOKUP_BLOB"	BLOB DEFAULT NULL, "UPDATE_DATE" TEXT DEFAULT NULL, "DOWNLOAD_DATE"	TEXT DEFAULT NULL, "IMPORT_DATE"	TEXT DEFAULT NULL, "SOURCESYSTEM_CD"	TEXT DEFAULT NULL, "UPLOAD_ID"	NUMERIC DEFAULT NULL, PRIMARY KEY("CODE_CD") )',
    CONCEPT_DIMENSION: 'CREATE TABLE "CONCEPT_DIMENSION" ( "CONCEPT_PATH"	TEXT, "CONCEPT_CD"	TEXT UNIQUE, "NAME_CHAR"	TEXT NOT NULL, "VALTYPE_CD"	TEXT, "UNIT_CD"	TEXT, "RELATED_CONCEPT"	TEXT, "CONCEPT_BLOB"	BLOB, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "SOURCESYSTEM_CD"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY("CONCEPT_CD") )',
    PATIENT_DIMENSION:'CREATE TABLE "PATIENT_DIMENSION" ( "PATIENT_NUM" INTEGER UNIQUE, "PATIENT_CD" TEXT UNIQUE, "VITAL_STATUS_CD" TEXT, "BIRTH_DATE" NUMERIC, "DEATH_DATE" NUMERIC, "AGE_IN_YEARS" NUMERIC, "SEX_CD" TEXT, "LANGUAGE_CD" TEXT, "RACE_CD" TEXT, "MARITAL_STATUS_CD" TEXT, "RELIGION_CD" TEXT, "STATECITYZIP_PATH" TEXT, "PATIENT_BLOB" BLOB, "UPDATE_DATE" TEXT, "DOWNLOAD_DATE" TEXT, "IMPORT_DATE" TEXT, "SOURCESYSTEM_CD" TEXT, "UPLOAD_ID" NUMERIC, PRIMARY KEY("PATIENT_NUM" AUTOINCREMENT) )',
    VISIT_DIMENSION: 'CREATE TABLE "VISIT_DIMENSION" ( "ENCOUNTER_NUM"	INTEGER UNIQUE, "PATIENT_NUM"	NUMERIC, "ACTIVE_STATUS_CD"	TEXT, "START_DATE"	NUMERIC, "END_DATE"	NUMERIC, "INOUT_CD"	TEXT, "LOCATION_CD"	TEXT, "VISIT_BLOB"	BLOB, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "SOURCESYSTEM_CD"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY("ENCOUNTER_NUM" AUTOINCREMENT) )',
    PROVIDER_DIMENSION: 'CREATE TABLE IF NOT EXISTS "PROVIDER_DIMENSION" ( "PROVIDER_ID"	TEXT, "PROVIDER_PATH"	TEXT, "NAME_CHAR"	TEXT, "CONCEPT_BLOB"	BLOB, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "SOURCESYSTEM_CD"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY ("PROVIDER_ID") );',
    OBSERVATION_FACT: 'CREATE TABLE "OBSERVATION_FACT" ( "OBSERVATION_ID"	INTEGER, "ENCOUNTER_NUM"	INTEGER NOT NULL, "PATIENT_NUM"	INTEGER NOT NULL, "CATEGORY_CHAR"	TEXT, "CONCEPT_CD"	TEXT, "PROVIDER_ID"	TEXT, "START_DATE"	TEXT, "INSTANCE_NUM"	NUMERIC, "VALTYPE_CD"	TEXT, "TVAL_CHAR"	TEXT, "NVAL_NUM"	NUMERIC, "VALUEFLAG_CD"	TEXT, "QUANTITY_NUM"	TEXT, "UNIT_CD"	TEXT, "END_DATE"	NUMERIC, "LOCATION_CD"	TEXT, "CONFIDENCE_NUM"	TEXT, "OBSERVATION_BLOB"	BLOB, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "SOURCESYSTEM_CD"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY("OBSERVATION_ID" AUTOINCREMENT), FOREIGN KEY("CONCEPT_CD") REFERENCES "CONCEPT_DIMENSION"("CONCEPT_CD") ON DELETE CASCADE ON UPDATE NO ACTION, FOREIGN KEY("ENCOUNTER_NUM") REFERENCES "VISIT_DIMENSION"("ENCOUNTER_NUM") ON DELETE CASCADE ON UPDATE NO ACTION, FOREIGN KEY("PATIENT_NUM") REFERENCES "PATIENT_DIMENSION"("PATIENT_NUM") ON DELETE CASCADE ON UPDATE NO ACTION);',
    USER_MANAGEMENT: 'CREATE TABLE "USER_MANAGEMENT" ( "USER_ID"	INTEGER UNIQUE, "COLUMN_CD"	TEXT, "USER_CD"	TEXT UNIQUE, "NAME_CHAR"	TEXT, "PASSWORD_CHAR"	TEXT, "USER_BLOB"	TEXT, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY("USER_ID" AUTOINCREMENT))',
    USER_PATIENT_LOOKUP: 'CREATE TABLE "USER_PATIENT_LOOKUP" ( "USER_PATIENT_ID"	INTEGER UNIQUE, "USER_ID"	INTEGER NOT NULL, "PATIENT_NUM"	INTEGER NOT NULL, "NAME_CHAR"	TEXT, "USER_PATIENT_BLOB"	TEXT, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "UPLOAD_ID"	NUMERIC, FOREIGN KEY("PATIENT_NUM") REFERENCES "PATIENT_DIMENSION"("PATIENT_NUM"), FOREIGN KEY("USER_ID") REFERENCES "USER_MANAGEMENT"("USER_ID"), PRIMARY KEY("USER_PATIENT_ID" AUTOINCREMENT));',
    CQL_FACT: 'CREATE TABLE "CQL_FACT" ( "CQL_ID"	INTEGER UNIQUE, "CODE_CD"	TEXT, "NAME_CHAR"	TEXT, "CQL_CHAR"	BLOB, "JSON_CHAR"	BLOB, "CQL_BLOB"	BLOB, "UPDATE_DATE"	TEXT, "IMPORT_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "UPLOAD_ID"	NUMERIC, PRIMARY KEY("CQL_ID" AUTOINCREMENT))',
    CONCEPT_CQL_LOOKUP: 'CREATE TABLE "CONCEPT_CQL_LOOKUP" ("CONCEPT_CQL_ID"	INTEGER, "CONCEPT_CD"	TEXT NOT NULL, "CQL_ID"	INTEGER NOT NULL, "NAME_CHAR"	TEXT, "RULE_BLOB"	TEXT, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "UPLOAD_ID"	NUMERIC, FOREIGN KEY("CONCEPT_CD") REFERENCES "CONCEPT_DIMENSION"("CONCEPT_CD"), FOREIGN KEY("CQL_ID") REFERENCES "CQL_FACT"("CQL_ID"), PRIMARY KEY("CONCEPT_CQL_ID" AUTOINCREMENT))',
    NOTE_FACT: 'CREATE TABLE "NOTE_FACT" ( "NOTE_ID"	INTEGER UNIQUE, "CATEGORY_CHAR"	TEXT, "NAME_CHAR"	TEXT, "NOTE_BLOB"	TEXT, "UPDATE_DATE"	TEXT, "DOWNLOAD_DATE"	TEXT, "IMPORT_DATE"	TEXT, "UPLOAD_ID" NUMERIC,PRIMARY KEY("NOTE_ID" AUTOINCREMENT))'

}




// CREATE TABLE "OBSERVATION_FACT" (
// 	"OBSERVATION_ID"	INTEGER,
// 	"ENCOUNTER_NUM"	INTEGER NOT NULL,
// 	"PATIENT_NUM"	INTEGER NOT NULL,
// 	"CATEGORY_CHAR"	TEXT,
// 	"CONCEPT_CD"	TEXT,
// 	"PROVIDER_ID"	TEXT,
// 	"START_DATE"	TEXT,
// 	"INSTANCE_NUM"	NUMERIC,
// 	"VALTYPE_CD"	TEXT,
// 	"TVAL_CHAR"	TEXT,
// 	"NVAL_NUM"	NUMERIC,
// 	"VALUEFLAG_CD"	TEXT,
// 	"QUANTITY_NUM"	TEXT,
// 	"UNIT_CD"	TEXT,
// 	"END_DATE"	NUMERIC,
// 	"LOCATION_CD"	TEXT,
// 	"CONFIDENCE_NUM"	TEXT,
// 	"OBSERVATION_BLOB"	BLOB,
// 	"UPDATE_DATE"	TEXT,
// 	"DOWNLOAD_DATE"	TEXT,
// 	"IMPORT_DATE"	TEXT,
// 	"SOURCESYSTEM_CD"	TEXT,
// 	"UPLOAD_ID"	NUMERIC,
// 	PRIMARY KEY("OBSERVATION_ID" AUTOINCREMENT),
// 	FOREIGN KEY("CONCEPT_CD") REFERENCES "CONCEPT_DIMENSION"("CONCEPT_CD") ON DELETE CASCADE ON UPDATE NO ACTION,
// 	FOREIGN KEY("ENCOUNTER_NUM") REFERENCES "VISIT_DIMENSION"("ENCOUNTER_NUM") ON DELETE CASCADE ON UPDATE NO ACTION,
// 	FOREIGN KEY("PATIENT_NUM") REFERENCES "PATIENT_DIMENSION"("PATIENT_NUM") ON DELETE CASCADE ON UPDATE NO ACTION);

// CREATE TABLE "CQL_FACT" (
// 	"CQL_ID"	INTEGER UNIQUE,
// 	"CODE_CD"	TEXT,
// 	"NAME_CHAR"	TEXT,
// 	"CQL_CHAR"	BLOB,
// 	"JSON_CHAR"	BLOB,
// 	"CQL_BLOB"	BLOB,
// 	"UPDATE_DATE"	TEXT,
// 	"IMPORT_DATE"	TEXT,
// 	"DOWNLOAD_DATE"	TEXT,
// 	"UPLOAD_ID"	INTEGER,
// 	PRIMARY KEY("CQL_ID" AUTOINCREMENT)
// )

// CREATE TABLE "CONCEPT_CQL_LOOKUP" (
// 	"RULE_ID"	INTEGER,
// 	"CONCEPT_CD"	TEXT NOT NULL,
// 	"CQL_ID"	INTEGER NOT NULL,
// 	"NAME_CHAR"	TEXT,
// 	"RULE_BLOB"	TEXT,
// 	"UPDATE_DATE"	TEXT,
// 	"DOWNLOAD_DATE"	TEXT,
// 	"IMPORT_DATE"	TEXT,
// 	"UPLOAD_ID"	NUMERIC,
// 	FOREIGN KEY("CONCEPT_CD") REFERENCES "CONCEPT_DIMENSION"("CONCEPT_CD"),
// 	FOREIGN KEY("CQL_ID") REFERENCES "CQL_FACT"("CQL_ID"),
// 	PRIMARY KEY("RULE_ID" AUTOINCREMENT)
// )


// CREATE TABLE "NOTE_FACT" (
// 	"NOTE_ID"	INTEGER UNIQUE,
// 	"CATEGORY_CHAR"	TEXT,
// 	"NAME_CHAR"	TEXT,
// 	"NOTE_BLOB"	TEXT,
// 	"UPDATE_DATE"	TEXT,
// 	"DOWNLOAD_DATE"	TEXT,
// 	"IMPORT_DATE"	TEXT,
// 	"UPLOAD_ID" NUMERIC,
// 	PRIMARY KEY("NOTE_ID" AUTOINCREMENT)
// )