CREATE VIEW patient_observations
AS

SELECT
   PATIENT_DIMENSION.PATIENT_CD as PATIENT_CD,
   PATIENT_DIMENSION.PATIENT_NUM as PATIENT_NUM,
   USER_PATIENT_LOOKUP.USER_ID as USER_ID,
   VISIT_DIMENSION.ENCOUNTER_NUM as ENCOUNTER_NUM,
   OBSERVATION_FACT.START_DATE as START_DATE,
   OBSERVATION_FACT.OBSERVATION_ID as OBSERVATION_ID,
   OBSERVATION_FACT.CATEGORY_CHAR as CATEGORY_CHAR,
   OBSERVATION_FACT.CONCEPT_CD as CONCEPT_CD,
   CD1.NAME_CHAR as CONCEPT_NAME_CHAR,
   OBSERVATION_FACT.VALTYPE_CD as VALTYPE_CD,
   OBSERVATION_FACT.NVAL_NUM as NVAL_NUM,
   OBSERVATION_FACT.UNIT_CD as UNIT_CD,
   OBSERVATION_FACT.TVAL_CHAR as TVAL_CHAR,
   CD2.NAME_CHAR as TVAL_RESOLVED,
   OBSERVATION_FACT.OBSERVATION_BLOB as OBSERVATION_BLOB,
   OBSERVATION_FACT.LOCATION_CD as LOCATION_CD,
   OBSERVATION_FACT.PROVIDER_ID as PROVIDER_ID
   
FROM
    OBSERVATION_FACT

INNER JOIN PATIENT_DIMENSION ON
	PATIENT_DIMENSION.PATIENT_NUM = OBSERVATION_FACT.PATIENT_NUM
INNER  JOIN VISIT_DIMENSION ON
	VISIT_DIMENSION.ENCOUNTER_NUM = OBSERVATION_FACT.ENCOUNTER_NUM
LEFT  JOIN CONCEPT_DIMENSION AS CD1 ON
	CD1.CONCEPT_CD = OBSERVATION_FACT.CONCEPT_CD
LEFT  JOIN CONCEPT_DIMENSION AS CD2 ON
	CD2.CONCEPT_CD = OBSERVATION_FACT.TVAL_CHAR	
	
LEFT JOIN USER_PATIENT_LOOKUP ON
	USER_PATIENT_LOOKUP.PATIENT_NUM = OBSERVATION_FACT.PATIENT_NUM
	
ORDER BY	PATIENT_CD, START_DATE, ENCOUNTER_NUM, OBSERVATION_ID