version: '3'
services:
  nodejs-email-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/mail_service/src/
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=