CREATE VIEW cql_concept_list
AS

SELECT
	CONCEPT_CQL_LOOKUP.CONCEPT_CQL_ID as CONCEPT_CQL_ID,
   CONCEPT_CQL_LOOKUP.CQL_ID as CQL_ID,
   CQL_FACT.CODE_CD as CQL_CODE_CD,
   CQL_FACT.NAME_CHAR as CQL_NAME_CHAR,
   CONCEPT_CQL_LOOKUP.CONCEPT_CD as CONCEPT_CD,
   CONCEPT_DIMENSION.NAME_CHAR as CONCEPT_NAME_CHAR
   
FROM
    CONCEPT_CQL_LOOKUP

INNER JOIN CONCEPT_DIMENSION ON
	CONCEPT_DIMENSION.CONCEPT_CD = CONCEPT_CQL_LOOKUP.CONCEPT_CD

INNER JOIN CQL_FACT ON
	CQL_FACT.CQL_ID = CONCEPT_CQL_LOOKUP.CQL_ID

ORDER BY	CONCEPT_CD